### ISSUE TITLE
can i use the edgex-go with this device-virtual?Thank you

### ISSUE THREAD

**Issue by caocaocaodou** [edgexfoundry/device-virtual#42]
can i use the edgex-go with this device-virtual? thank you!

**Comment by jpwhitemn** [comment]
@caocaocaodou - yes.  Delhi docker-compose file does this by default.

**Comment by caocaocaodou** [comment]
@jpwhitemn what about if i do not use docker？Thank you！

**Comment by jpwhitemn** [comment]
@caocaocaodou - you can run any EdgeX service outside of Docker.  This may require you to do some additional work such as install a JVM for the Java device-virtual and configure the services to point to the correct IP addresses or host names as the Docker network and container names will not be in place, but EdgeX does not require containerization.  You may want to read the Hybrid developers guide for some background and help:  https://docs.edgexfoundry.org/Ch-GettingStartedHybrid.html.

**Comment by caocaocaodou** [comment]
thank you very much！
